config/routes.rb
Scs::Application.routes.draw do

  devise_for :gods

  devise_for :admins

  resources :accounts

  resources :all_orders, :only => [] do
    collection do
      post 'generate'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end

  resources :locations

  resources :settings

  resources :counts

  resources :checks do
    collection do
      put 'refresh_count', 'color_update', 'generate', 'upload_ins'
      get 'color', 'reimport', 'to_generate', 'instruction'
    end

    member do
      put 'make_current'
    end

    resources :reports, :only => [] do
      collection do
        get 'count_varience', 'count_frozen', 'tags', 'inventories', 'remote_warehouse_by_item', 'remote_warehouse_by_warehouse'
      end
    end
  end

  namespace :audit do
    resources :tags
  end

  namespace :dataentry do
    resources :inventories
    resources :items do
      resources :inventories
    end
  end

  namespace :god do
    resources :rechecks

    resources :checks do
      resources :activities
      resources :tags
      resources :inventories
      
      collection do
        get 'current', 'history', 'import_cost'
        put 'do_import_cost'
      end

      put 'change_state', :on => :member
    end
  end

  namespace :adm do
    resources :wait_prints do
      get 'multiple_create', :on => :collection
    end

    resources :items do
      resources :tags

      get 'missing_cost', :on => :collection

      member do
        get 'input_price'
        put 'update_price'
      end
    end

    resources :tags do
      get 'adj_list', :on => :collection

      member do
        get 'to_adj'
        put 'update_adj'
      end
    end

    resources :counters

    resources :items do
      resources :inventories, :only => [:new, :create]
    end

    resources :inventories do
      resources :tags
    end

    resources :counts do
      get 'missing_tag', 'result', :on => :collection
    end

    resources :locations do
      resources :assigns
    end
  end

  root :to => "dashboards#show"

end

app/controllers/adm/base_controller.rb
class Adm::BaseController < ApplicationController
  before_filter {check_role [:organizer, :controller, :mgt]}
end

app/controllers/adm/counters_controller.rb
class Adm::CountersController < Adm::BaseController
  layout "tags"

  before_filter do
    @sub_menu = :counters
  end
  # GET /counters
  # GET /counters.xml
  def index
    @counters = Counter.order("name ASC").all
  end

  # GET /counters/1
  # GET /counters/1.xml
  def show
    @counter = Counter.find(params[:id])
  end

  # GET /counters/new
  # GET /counters/new.xml
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
    @counter = Counter.find(params[:id])
  end

  # POST /counters
  # POST /counters.xml
  def create
    @counter = Counter.new(params[:counter])

    @counter.new_assigns, @counter.curr_check = get_count_assigns(:location), curr_check
    respond_to do |format|
      if @counter.save
        format.html { redirect_to(adm_counters_path, :notice => 'Counter was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /counters/1
  # PUT /counters/1.xml
  def update
    @counter = Counter.find(params[:id])

    @counter.new_assigns, @counter.curr_check = get_count_assigns(:location), curr_check

    respond_to do |format|
      if @counter.update_attributes(params[:counter])
        format.html { redirect_to(adm_counters_path, :notice => 'Counter was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.xml
  def destroy
    @counter = Counter.find(params[:id])
    @counter.destroy

    respond_to do |format|
      format.html { redirect_to(adm_counters_path) }
    end
  end
end

app/controllers/adm/counts_controller.rb
require 'ext/tag_table'
require 'ext/spreadsheet'

class Adm::CountsController < Adm::BaseController
  layout "tags"

  before_filter do
    @c_i = (params[:count] || "1").to_i
    @c_s = "count_#{@c_i.to_s}".to_sym
  end

  def missing_tag
    @search = Tag.in_check(curr_check.id).not_finish(@c_i).countable.search(params[:search])

    respond_to do |format|
      format.html { @tags = @search.paginate(:page => params[:page]) }
      format.pdf {
        @tags = @search.all

        pdf = Prawn::Document.generate_tags @tags
        send_data pdf.render, :filename => "tags.pdf", :disposition => 'attachment'
      }
      format.xls {
        @tags = @search.all
        book = Spreadsheet::Workbook.new

        data = book.generate_xls(
        "Missing Tags Count #{@c_i}", @tags,        
        ['Tag #', 'Item #', 'Warehouse', 'Shelf Location', @c_s.to_s],
        [:id, [:inventory, :item, :code], [:inventory, :location, :code], :sloc, @c_s]
        )

        send_data data, :filename => "Missing Tags Count #{@c_i}.xls", :disposition => 'attachment'
      }

    end
  end

  def result
    @search = Tag.in_check(curr_check.id).countable.where(@c_s.gte % 0).search(params[:search])

    respond_to do |format|
      format.html { 
        @tags = @search.paginate(:page => params[:page])
      }
      format.xls {
        @tags = @search.all
        book = Spreadsheet::Workbook.new
        data = book.generate_xls("Count #{@c_s} Result", @tags, 
        %w{TagNumber ItemNumber Description Warehouse ShelfLocation Count},
        [:id,
        [:inventory, :item, :code], 
        [:inventory, :item, :description],
        [:inventory, :location, :code],
        :sloc,
        @c_s])
        send_data data, :filename => "Count #{@c_i} Result.xls", :disposition => 'attachment'
      }
    end
  end
end

app/controllers/adm/inventories_controller.rb
class Adm::InventoriesController < Adm::BaseController
  layout 'tags'

  def show
    @inventory = curr_check.inventories.remote_s.find(params[:id])
  end

  def new
    @item = curr_check.items.find(params[:item_id])
    @inventory = @item.inventories.new
  end

  def create
    @item = curr_check.items.find(params[:item_id])
    @inventory = @item.inventories.build(params[:inventory])
    
    if @inventory.save
      redirect_to adm_inventories_path, :notice => "Remote Ticket R-#{@inventory.id} Created."
    else
      render :new
    end
  end

  def index
    @search = curr_check.inventories.remote_s.search(params[:search])

    respond_to do |format|
      format.html { @inventories = @search.paginate(:page => params[:page]) }
      format.xls {
        @inventories = @search.all
        book = Spreadsheet::Workbook.new

        data = book.generate_xls(
        "Remote Warehouse Tickets", @inventories,
        %w{Ticket# Warehouse Item# Desc. FrozenQty ScsQty},
        [:remote_ticket_id,
          [:location, :code],
          [:item, :code],
          [:item, :description],
          :quantity,
          :inputed_qty]
        )
        
        send_data data, :filename => "Remote Warehouse Tickets.xls", :disposition => 'attachment'
      }
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    
    if @inventory.update_attributes(params[:inventory])
      if request.xhr?
        render :partial => 'inputed_qty', :locals => {:inventory => @inventory}
      else
        redirect_to adm_inventories_path, :notice => "Inputed successfully."
      end
    else
      render :edit
    end
  end
end

app/controllers/adm/items_controller.rb
class Adm::ItemsController < Adm::BaseController
  layout "tags"

  def new
    @item = curr_check.items.new(params[:item])
  end
  
  def edit
    @item = curr_check.items.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to missing_cost_adm_items_path(:sub_menu => :missing_cost), :notice => "Cost has been updated."
    else
      render :edit
    end
  end
  
  def create
    @item = curr_check.items.build(params[:item])
    @item.from_al = false
    
    if @item.save
      redirect_to adm_items_path, :notice => "Item #{@item.code} has been created."
    else
      render :new
    end
  end
  
  def show
    @item = curr_check.items.find(params[:id])
  end

  def index
    @search = curr_check.items.search(params[:search])
    @items = @search.paginate(:page => params[:page])
    
    if params[:search] && @search.count == 0
      @error_m = "Nothing found. <br />1.) Fix it now! Re-check the part number / item (Recommended) <br />2.) Fix it later. Create ticket (list for resolution with All Order)"
    end
  end

  def input_price
    @item = curr_check.items.find(params[:id])
  end

  def update_price
    @item = Item.find(params[:id])
    # @item = curr_check.items.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to( missing_cost_adm_items_path, :notice => 'Cost was successfully updated.')
    else
      render :action => "input_price"
    end
  end

  def missing_cost
    @search = curr_check.items.missing_cost.search(params[:search])

    respond_to do |format|
      format.html { @items = @search.paginate(:page => params[:page]) }
      format.xls {
        @items = @search.all
        book = Spreadsheet::Workbook.new
        
        data = book.generate_xls(
        "Missing Cost", @items,        
        %w{ItemNumber Desc. Cost},
        [:code, :description, :cost]
        )

        send_data data, :filename => "Missing Cost.xls", :disposition => 'attachment'
      }
    end

  end
end

app/controllers/adm/locations_controller.rb
require 'ext/spreadsheet'

class Adm::LocationsController < Adm::BaseController
  layout "tags"
  
  before_filter { @sub_menu = :items }

  def new
    @location = Location.new
  end

  def index
    @search = curr_check.locations.tagable.search(params[:search])
    
    respond_to do |format|
      format.html {
        @locations = @search.paginate(:page => params[:page])
      }
      format.xls {
        @locations = @search.all
        send_data Spreadsheet::Workbook.new.render_location_counters(@locations), 
        :filename => "Counter_by_Location.xls", :disposition => 'attachment'
      }
    end
  end

  def show
  end

  def create
    @location = curr_check.locations.build(params[:location])
    @location.is_remote = false

    respond_to do |format|
      if @location.save
        format.html { redirect_to( adm_counters_path, :notice => 'Onsite Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_path, :notice => "Location has been deleted.") }
      format.xml  { head :ok }
    end
  end
  
  def edit
    @location = curr_check.locations.find(params[:id])
  end
  
  def update
    @location = Location.find(params[:id])

    assigns = []
    Counter.all.each do |counter|
      if params[:count][counter.id.to_s].to_i > 0 && params[:count][counter.id.to_s].to_i < 3
        assigns << Assign.new(:count => params[:count][counter.id.to_s], :counter => counter)
      end
    end
    @location.new_assigns, @location.curr_check = assigns, curr_check

    if @location.update_attributes(params[:location])
      redirect_to locations_path, :notice => "Location #{@location.code} has been updated."
    else
      render :edit
    end
  end
  
end

app/controllers/adm/tags_controller.rb
require 'ext/tag_table'

class Adm::TagsController < Adm::BaseController
  layout "tags"

  # GET /tags
  # GET /tags.xml
  def index    
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])

    respond_to do |format|
      format.html { @tags = @search.paginate(:page => params[:page]) }

      format.pdf {
        @tags = @search.all

        pdf = Prawn::Document.generate_tags @tags
        send_data pdf.render, :filename => "tickets.pdf", :disposition => 'attachment'
      }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    if params[:inventory_id]
      inventory = Inventory.find(params[:inventory_id])
      @tag.item_id, @item = inventory.item.id, inventory.item
      @tag.location_id = inventory.location.id
    elsif params[:item_id]
      @tag.item_id, @item = params[:item_id].to_i, Item.find(params[:item_id])
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @item = @tag.inventory.item
    @tag.item_id = @item.id
    @tag.location_id = @tag.inventory.location.id
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to adm_tags_path, :notice => "Ticket No.#{@tag.id} was successfully created." }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])
    
    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to( adm_tag_path(@tag), :notice => 'Ticket was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @tag.update_attributes(:state => "deleted")

    respond_to do |format|
      format.html { redirect_to(adm_tags_url, :notice => "Deleted successfully.") }
      format.xml  { head :ok }
    end
  end

  def adj_list
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])
    @tags = @search.paginate(:page => params[:page])
  end

  def to_adj
    @check = curr_check

    @tag = Tag.in_check(@check.id).find(params[:id])
  end

  def update_adj
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    
    if @tag.update_attributes(:adjustment => (params[:tag] || {})[:adjustment])
      redirect_to adj_list_adm_tags_path, :notice => "Updated."
    else
      render :adj_list
    end
  end

end

app/controllers/adm/wait_prints_controller.rb
require 'ext/tag_table'

class Adm::WaitPrintsController < Adm::BaseController
  layout "tags"

  before_filter do
    @sub_menu = :print_list
  end

  def destroy
    @tag = Tag.in_check(curr_check.id).find(params[:id])

    if @tag.update_attributes(:wait_for_print => false)
      redirect_to adm_wait_prints_path, :notice => "Successfully removed."
    else
      redirect_to adm_wait_prints_path, :alert => "Failed to remove."
    end
  end

  def update
    @tag = Tag.in_check(curr_check.id).find(params[:id])

    if @tag.update_attributes(:wait_for_print => true)
      redirect_to adm_wait_prints_path, :notice => "One ticket successfully added."
    else
      redirect_to adm_tags_path, :alert => "Failed to add."
    end
  end

  def multiple_create
    @search = Tag.in_check(curr_check.id).countable.where(:wait_for_print => false).readonly(false).search(params[:search])
    count = @search.count

    @search.each { |tag|
      tag.update_attributes(:wait_for_print => true)
    }

    redirect_to adm_wait_prints_path, :notice => "#{count} tickets successfully added."
  end

  def index
    @search = Tag.in_check(curr_check.id).where(:wait_for_print => true).readonly(false).search(params[:search])

    respond_to do |format|
      format.html { @tags = @search.paginate(:page => params[:page]) }
      format.js {
        file = StringIO.new(Prawn::Document.generate_tags(@search.all).render)
        file.class.class_eval { attr_accessor :original_filename, :content_type } #add attr's that paperclip needs
        file.original_filename = "generated_pdf_#{curr_check.generated_pdfs.count + 1}.pdf"
        file.content_type = "application/pdf"

        @attachment = ::Attachment.create(:data => file)
        curr_check.generated_pdfs << @attachment

        render :partial => 'adm/wait_prints/download_link', :locals => {:attachment => @attachment}
        # send_data pdf.render, :filename => "tickets.pdf", :disposition => 'attachment'
      }
    end
  end
end

app/controllers/audit/tags_controller.rb
require 'ext/spreadsheet'

class Audit::TagsController < Audit::BaseController
  before_filter do
    @nav = :audit
  end

  def edit
    @tag = Tag.in_check(curr_check.id).countable.find(params[:id])
  end

  def index
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])
    @tags = @search.paginate(:page => params[:page])
  end
  
  def update
    @tag = Tag.in_check(curr_check.id).countable.find(params[:id])
    
    if @tag.update_attributes(params[:tag])
      redirect_to audit_tags_path, :notice => "Audit updated."
    else
      render :edit
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/adm/tags/_form.html.erb
<%= form_for @tag, :url => @tag.new_record? ? adm_tags_path : adm_tag_path(@tag), :html => {:class => 'uniform'} do |f| %>
	<%= render :partial => "shared/errors", :locals => {:object => @tag} %>

	<fieldset>
		<legend>Choose Location</legend>
		<dl class="inline">
			<dt><%= f.label :item_id, 'Item Number' %></dt>
			<dd>
				<%= f.label :item_id, @item.code %>
				<%= f.hidden_field :item_id %>
			</dd>
			<dt><%= f.label :item_description %></dt>
			<dd>
				<%= f.label :item_description, @item.description %>
			</dd>
			<dt><%= f.label :location_id, 'Onsite Warehouse' %></dt>
			<dd>
				<%= f.collection_select(:location_id, curr_check.locations.tagable, :id, :code, {:include_blank => false}, {:class => "small", :tabindex => 1})  %>
				<%= link_to "New Onsite Warehouse", new_adm_location_path %>
			</dd>
			<dt><%= f.label :sloc, 'Shelf Location' %></dt>
			<dd><%= f.text_field :sloc, :tabindex => 2, :class => 'small' %></dd>
		</dl>
	</fieldset>
	<div class="buttons">
		<%= f.submit "Save", :class => 'button' %>
	</div>

<% end %>

app/views/adm/tags/adj_list.html.erb
<% @sub_menu = :final_qty %>
<article>
	<%= render :partial => 'shared/flash' %>
	<%= form_for @search, :url => adj_list_adm_tags_path do |f| %>
	<%= hidden_field_tag :check_id, params[:check_id] %>
		<fieldset>
			<legend>Search</legend>
			<dl class="inline">
				<%= render :partial => 'tags/search_dl', :locals => {:f => f, :check => curr_check} %>
			</dl>
			<div class="buttons">
				<%= f.submit 'Search', :class => "button" %>
			</div>
		</fieldset>
	<% end %>
</article>

<article>
	<h1><%= @search.count %> Tickets</h1>

	<table class="gtable detailtable">
		<thead>
			<tr>
				<th><%= sort_link @search, :id, 'Ticket #' %></th>
				<th><%= sort_link @search, :count_1 %></th>
				<th><%= sort_link @search, :count_2 %></th>
				<th><%= sort_link @search, :count_3 %></th>
				<th><%= sort_link @search, :adjustment, 'Manual Adjustment' %></th>
				<th><%= sort_link @search, :final_count, 'Final' %></th>
				<th>Action</th>
			</tr>
		</thead>
		
		<tbody>
			<% @tags.each do |tag| %>
			<% next unless tag.inventory %>
			<tr>
				<td>
				<a href="#" class="detail-link"><%= tag.id %></a>	
				</td>
				<td><%= tag.count_1 %></td>
				<td><%= tag.count_2 %></td>
				<td><%= tag.count_3 %></td>
				<td><%= tag.adjustment %></td>
				<td><%= tag.final_count %></td>
				<td>
					<%= link_to image_tag('icons/edit.png'), to_adj_adm_tag_path(tag), :title => 'Setup Final' if allow_data_entry? %>
				</td>
			</tr>
			<tr class="detail">
				<td colspan="7">
					<table>
						<tbody>
							<tr>
								<td><%= tag.inventory.location.try(:code) %></td>
								<td><%= tag.inventory.item.try(:code) %></td>
								<td><%= tag.inventory.item.try(:description) %></td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<% end %>

		</tbody>
	</table>
	
	<div class="tablefooter clearfix">
		<%= will_paginate @tags %>
	</div>
</article>

app/views/adm/tags/edit.html.erb
<% @sub_menu = :tags %>
<article>
<h1>Editing Ticket</h1>

<%= render 'form' %>
</article>

app/views/adm/tags/index.html.erb
<% @sub_menu = :tags %>

<article>
	<%= render :partial => 'shared/flash' %>
	<%= form_for @search, :url => adm_tags_path do |f| %>
		<fieldset>
			<legend>Search</legend>
			<dl class="inline">
				<%= render :partial => 'tags/search_dl', :locals => {:f => f, :check => curr_check} %>
			</dl>
			<div class="buttons">
				<%= f.submit 'Search', :class => "button" %>
				<%= link_to 'Reset', adm_tags_path, :class => 'button' %>
			</div>
		</fieldset>
	<% end %>
</article>

<article>
	<h1><%= @search.count %> Tickets, <%= @search.where(:wait_for_print => false).count %> tickets not in the print list.</h1>
	<!-- loading_link 'Print tickets (PDF)', url_for(request.params.merge(:format => :pdf)), :class => 'button' -->

	<%= loading_link "Add the #{@search.where(:wait_for_print => false).count} tickets to the print list", multiple_create_adm_wait_prints_path(:search => params[:search]), :confirm => "Are you sure to add the #{@search.where(:wait_for_print => false).count} tickets to the print list?", :class => 'button', :message => 'processing...' %>

	<table class="gtable detailtable">
		<thead>
			<tr>
				<th><%= sort_link @search, :id, 'Ticket #' %></th>
				<th><%= sort_link @search, :inventory_item_code, 'Item #' %></th>
				<th><%= sort_link @search, :inventory_location_code, 'Warehouse' %></th>
				<th><%= sort_link @search, :inventory_item_cost, 'Cost' %></th>
				<th><%= sort_link @search, :sloc, 'Shelf Loc' %></th>
				<th><%= sort_link @search, :printed_time, 'Printed' %></th>
				<th>Action</th>
			</tr>
		</thead>
		
		<tbody>
			<% @tags.each do |tag| %>
			<% next unless tag.inventory %>
			<tr>
				<td><%= tag.id %></td>
				<td><%= tag.inventory.item.try(:code) %> <a href="#" class="detail-link">more</a></td>
				<td><%= tag.inventory.location.try(:code) %></td>
				<td class='number'><%=number_to_currency (tag.inventory.item.try(:cost) || 0) %></td>
				<td><%= tag.sloc %></td>
				<td><%= tag.printed_time.to_i > 0 ? "√ (#{tag.printed_time.to_i})" : "X" %> </td>
				<td>
					<% if allow_data_entry? %>

					<ul class="actions">
						<li>
							<%= link_to image_tag('icons/cross.png'), adm_tag_path(tag), :method => :delete, :confirm => "Are you sure to delete Ticket #{tag.id}?", :title => 'Delete' %>
						</li>
						<li>
							<%= link_to image_tag('icons/edit.png'), edit_adm_tag_path(tag), :title => 'Edit' %>
						</li>
						<li>
							<%= link_to image_tag('icons/add.png'), adm_wait_print_path(tag), :method => :put, :confirm => "Are you sure to add Ticket #{tag.id} to print list?", :title => 'Add to print list.' unless tag.wait_for_print %>
							<%= image_tag('icons/edit_remove.png', :title => 'Already in the print list') if tag.wait_for_print %>
						</li>
					</ul>

					<% end %>
				</td>
			</tr>
			<tr class="detail">
				<td colspan="7">
					<table>
						<tbody>
							<tr>
								<td><%= tag.inventory.item.try(:description) %></td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<% end %>

		</tbody>
	</table>
	
	<div class="tablefooter clearfix">
		<%= will_paginate @tags %>
	</div>
</article>

app/views/adm/tags/new.html.erb
<% @sub_menu = :items %>
<article>
	<h1>New Ticket</h1>
	<%= render 'form' %>
</article>

app/views/adm/tags/show.html.erb
<% @sub_menu = :tags %>
<article>
<%= render :partial => "shared/flash" %>
<table class="infos">
	<tr>
		<th>Ticket Number</th>
		<td><%= @tag.id %></td>
	</tr>
	<tr>
		<th>Item Number</th>
		<td><%= @tag.inventory.item.try(:code) %></td>
	</tr>
	<tr>
		<th>Description</th>
		<td><%= @tag.inventory.item.try(:description) %></td>
	</tr>
	<tr>
		<th>Onsite Warehouse</th>
		<td><%= @tag.inventory.location.try(:code) %></td>
	</tr>
	<tr>
		<th>Shelf Location</th>
		<td><%= @tag.try(:sloc) %></td>
	</tr>
	<tr>
		<th>Created Date</th>
		<td><%= @tag.created_at.to_date %></td>
	</tr>
</table>

<div class="tablefooter clearfix">
	<div class="actions">
	<%= link_to image_tag('icons/printer.png'), adm_tags_path(:search => {:id_eq => @tag.id}, :format => :pdf) %>
	</div>
</div>
</article>

app/views/adm/tags/to_adj.html.erb
<article>
	
	<h1>Setup Final Qty</h1>
	<%= form_for @tag, :url => update_adj_adm_tag_path(@tag), :html => {:class => 'uniform'} do |f| %>
		<%= render :partial => "shared/errors", :locals => {:object => @tag} %>

		<fieldset>
			<legend>Entry</legend>
			<dl class="inline">
				<dt><%= f.label :id, 'Ticket #' %></dt>
				<dd><%= f.label :id, @tag.id %></dd>

				<dt><%= f.label :location_code, 'Onsite Warehouse' %></dt>
				<dd><%= f.label :location_code, @tag.inventory.location.try(:code) %></dd>

				<dt><%= f.label :item_id, 'Item #' %></dt>
				<dd><%= f.label :item_id, @tag.inventory.item.code %></dd>
				<dt><%= f.label :item_description, 'Desc.' %></dt>
				<dd><%= f.label :item_description, @tag.inventory.item.description %></dd>
				<dt><%= f.label :count_1 %></dt>
				<dd><%= f.label :count_1, @tag.count_1 || 0 %></dd>
				<dt><%= f.label :count_2 %></dt>
				<dd><%= f.label :count_2, @tag.count_2 || 0 %></dd>
				<dt><%= f.label :count_3 %></dt>
				<dd><%= f.label :count_3, @tag.count_3 || 0 %></dd>
				<dt><%= f.label :final %></dt>
				<dd><%= f.label :final, @tag.final_count || 0 %></dd>

				<dt><%= f.label :adjustment, 'Manual Adjustment' %></dt>
				<dd><%= f.text_field :adjustment, :class => "small", :tabindex => 1 %></dd>


			</dl>
		</fieldset>
		<div class="buttons">
			<%= f.submit "Save", :class => 'button' %>
		</div>

	<% end %>
	
</article>

app/views/adm/tags/to_import.html.erb
<% @sub_menu = :import %>
<article>
	<h1>Import from All Order</h1>

	<%= form_tag import_adm_tags_path, :method => :post, :class => 'uniform', :multipart => true do %>
	<fieldset>
		<legend>Form</legend>
		<dl class="inline">
			<dt><label for="upload">Excel/CSV</label></dt>
			<dd><%= file_field_tag :file %></dd>
		</dl>
		<div class="buttons">
			<%= submit_tag 'Import', :class => 'button' %>
		</div>
	</fieldset>
	<% end %>
</article>