config/routes.rb
Scs::Application.routes.draw do

  devise_for :gods

  devise_for :admins

  resources :accounts

  resources :all_orders, :only => [] do
    collection do
      post 'generate'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end

  resources :locations

  resources :settings

  resources :counts

  resources :checks do
    collection do
      put 'refresh_count', 'color_update', 'generate', 'upload_ins'
      get 'color', 'reimport', 'to_generate', 'instruction'
    end

    member do
      put 'make_current'
    end

    resources :reports, :only => [] do
      collection do
        get 'count_varience', 'count_frozen', 'tags', 'inventories', 'remote_warehouse_by_item', 'remote_warehouse_by_warehouse'
      end
    end
  end

  namespace :audit do
    resources :tags
  end

  namespace :dataentry do
    resources :inventories
    resources :items do
      resources :inventories
    end
  end

  namespace :god do
    resources :rechecks

    resources :checks do
      resources :activities
      resources :tags
      resources :inventories
      
      collection do
        get 'current', 'history', 'import_cost'
        put 'do_import_cost'
      end

      put 'change_state', :on => :member
    end
  end

  namespace :adm do
    resources :wait_prints do
      get 'multiple_create', :on => :collection
    end

    resources :items do
      resources :tags

      get 'missing_cost', :on => :collection

      member do
        get 'input_price'
        put 'update_price'
      end
    end

    resources :tags do
      get 'adj_list', :on => :collection

      member do
        get 'to_adj'
        put 'update_adj'
      end
    end

    resources :counters

    resources :items do
      resources :inventories, :only => [:new, :create]
    end

    resources :inventories do
      resources :tags
    end

    resources :counts do
      get 'missing_tag', 'result', :on => :collection
    end

    resources :locations do
      resources :assigns
    end
  end

  root :to => "dashboards#show"

end

app/views/shared/_curr_check.html.erb
<% if has_curr_check? %>
<table class="infos">
	<tbody>
		<tr>
			<th sytle="width:30%">Inventory name</th>
			<td><%= curr_check.description %></td>
		</tr>
		<tr>
			<th>Status</th>
			<td><%= curr_check.state %></td>
		</tr>
		
		<tr>
			<th>Launched by</th>
			<td><%= curr_check.admin.try(:username) %></td>
		</tr>
		<tr>
			<th>Start time</th>
			<td><%=l curr_check.start_time, :format => :long unless curr_check.start_time.nil? %></td>
		</tr>
		<tr>
			<th>Duration</th>
			<td><%= distance_of_time_in_words(curr_check.duration) %></td>
		</tr>
		<tr>
			<th>Missing cost</th>
			<td><strong><%= curr_check.items.missing_cost.count %></strong></td>
		</tr>
		<tr>
			<th>Remote Warehouse</th>
			<td><strong><%= Inventory.in_check(curr_check.id).remote_s.where(:inputed_qty.eq => nil).count %></strong></td>
		</tr>
		<tr>
			<th>Recheck (Number of Discrepancy)</th>
			<td>
				<strong><%= Inventory.in_check(curr_check.id).where(:re_export_offset.not_eq => 0).count %></strong>
				<%= link_to 'view list', god_rechecks_path %>
			</td>
		</tr>
	</tbody>
</table>

<h2>Tickets</h2>
<table class="infos">
	<thead>
		<tr style="text-align: right">
			<th>&nbsp;</th>
			<th>Issued</th>
			<th>Deleted</th>
			<th>Finished</th>
			<th>Outstanding</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Count 1</th>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).count %></td>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).deleted_s.count %></td>
			<td class="number"><%= Tag.in_check(curr_check.id).finish(1).count %></td>
			<td class="number">
			<strong>
			<%= Tag.in_check(curr_check.id).countable.not_finish(1).count %>
			</strong>
			</td>
		</tr>
		<tr>
			<th>Count 2</th>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).count %></td>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).deleted_s.count %></td>
			<td class="number"><%= Tag.in_check(curr_check.id).finish(2).count %></td>
			<td class="number">
			<strong>
			<%= Tag.in_check(curr_check.id).countable.not_finish(2).count %>
			</strong>
			</td>
		</tr>
		<tr>
			<th>Count 3</th>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).count %></td>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).deleted_s.count %></td>
			<td class="number"><%= Tag.in_check(curr_check.id).countable.finish(3).count %></td>
			<td class="number">0</td>
		</tr>
		<!--tr>
			<th></th>
			<td class="number"><%= all_wh = Inventory.in_check(curr_check.id).remote_s.count %></td>
			<td class="number">0</td>
			<td class="number"><%= fi_wh = Inventory.in_check(curr_check.id).remote_s.where(:inputed_qty.not_eq => nil).count %></td>
			<td class="number">
			<strong>
			<%= all_wh - fi_wh %>
			</strong>
			</td>
		</tr-->
		<tr>
			<th>Audit check</th>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).count %></td>
			<td class="number"><%= Tag.raw_in_chk(curr_check.id).deleted_s.count %></td>
			<td class="number"><%= Tag.in_check(curr_check.id).countable.where(:audit.not_eq => nil).count %></td>
			<td class="number">0</td>
		</tr>

	</tbody>
</table>

<% end %>

app/views/shared/_errors.html.erb
<% if object && object.errors.any? %>
	<div class="error msg">
		<%= pluralize(object.errors.count, "error") %> prohibited this from being saved:
		<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
	</div>	
<% end %>

app/views/shared/_flash.html.erb
<% if notice %>
<div class="information msg">
<%= notice %>
</div>
<div class="clear"></div>
<% end %>

<% if alert %>
<div class="error msg">
<%= alert %>
</div>
<div class="clear"></div>
<% end %>

<% if @error_m %>
<div class="error msg">
<%=raw @error_m %>
</div>
<div class="clear"></div>
<% end %>

app/views/shared/_inventory_ul.html.erb
<ul>
	<% if curr_check && curr_check.state == 'open' %>
	<li <%= "class='current'" if @sub_menu == :missing_cost %>><%= link_to "Missing Cost (#{curr_check.items.missing_cost.count})", missing_cost_adm_items_path %></li>
	<% end %>
	<li>
		<%= link_to "Onsite Tickets", adm_tags_path %>
		<ul>
		<li <%= "class='current'" if @sub_menu == :tags %>><%= link_to "Tickets (Edit / Delete)", adm_tags_path %></li>
		<% if allow_data_entry? %>
		<li <%= "class='current'" if @sub_menu == :items %>><%= link_to "Create Onsite Ticket", adm_items_path(:sub_menu => :items, :type => :onsite) %></li>
		<% end %>
		<li <%= "class='current'" if @sub_menu == :print_list %>><%= link_to "Print list (#{Tag.in_check(curr_check.id).ready_to_print.count} to print)", adm_wait_prints_path %></li>
		<li <%= "class='current'" if @sub_menu == :missing_count_1 %>><%= link_to "Count 1 Missing Tickets (#{Tag.in_check(curr_check.id).not_finish(1).countable.count})", missing_tag_adm_counts_path(:count => 1) %></li>
		<li <%= "class='current'" if @sub_menu == :result_count_1 %>><%= link_to "Count 1 Result (#{Tag.in_check(curr_check.id).finish(1).countable.count})", result_adm_counts_path(:count => 1) %></li>
		<li <%= "class='current'" if @sub_menu == :missing_count_2 %>><%= link_to "Count 2 Missing Tickets (#{Tag.in_check(curr_check.id).not_finish(2).countable.count})", missing_tag_adm_counts_path(:count => 2) %></li>
		<li <%= "class='current'" if @sub_menu == :result_count_2 %>><%= link_to "Count 2 Result (#{Tag.in_check(curr_check.id).finish(2).countable.count})", result_adm_counts_path(:count => 2) %></li>
		<li <%= "class='current'" if @sub_menu == :result_count_3 %>><%= link_to "Count 3 Result (#{Tag.in_check(curr_check.id).finish(3).countable.count})", result_adm_counts_path(:count => 3) %></li>
		<li <%= "class='current'" if @sub_menu == :final_qty %>><%= link_to "Final adjustment input", adj_list_adm_tags_path %></li>
		</ul>
	</li>
	<li <%= "class='current'" if @sub_menu == :remote %>><%= link_to "Remote Warehouses Tickets (#{curr_check.inventories.remote_s.where(:inputed_qty => nil).count})", adm_inventories_path %></li>
	<li <%= "class='current'" if @sub_menu == :counters %>><%= link_to "Participants (#{Counter.count})", adm_counters_path %></li>
	<li>
		<a href='#'>Reports</a>
		<ul>
			<li <%= "class='current'" if @sub_menu == :variance %>><%= link_to 'Variance Count 1 VS 2', count_varience_check_reports_path(curr_check) %></li>
			<li <%= "class='current'" if @sub_menu == :count_1_frozen %>><%= link_to 'Count Result VS Frozen QTY', count_frozen_check_reports_path(curr_check) %></li>
			<li <%= "class='current'" if @sub_menu == :report_tags %>><%= link_to 'Summary of counts by location', tags_check_reports_path(curr_check) %></li>
			<li <%= "class='current'" if @sub_menu == :report_inventories %>><%= link_to 'Summary by counts by value', inventories_check_reports_path(curr_check) %></li>

			<li <%= "class='current'" if @sub_menu == :remote_tickets_by_item %>><%= link_to 'Remote Tickets by Item', remote_warehouse_by_item_check_reports_path(curr_check) %></li>
			<li <%= "class='current'" if @sub_menu == :remote_tickets_by_warehouse %>><%= link_to 'Remote Tickets by Warehouse', remote_warehouse_by_warehouse_check_reports_path(curr_check) %></li>

		</ul>
	</li>
</ul>

app/views/shared/_settings_ul.html.erb
<ul>
	<% if has_curr_check? %>
	<li <%= "class='current'" if @sub_menu == :basic %>><%= link_to 'Basic Setup', edit_god_check_path(curr_check) %></li>
	<li <%= "class='current'" if @sub_menu == :location %>><%= link_to 'Remote Warehouse Setup', locations_path %></li>
	<li <%= "class='current'" if @sub_menu == :account %>><%= link_to 'Access Level Setup', accounts_path %></li>
	<% end %>
</ul>