config/routes.rb
Scs::Application.routes.draw do

  devise_for :gods

  devise_for :admins

  resources :accounts

  resources :all_orders, :only => [] do
    collection do
      post 'generate'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end

  resources :locations

  resources :settings

  resources :counts

  resources :checks do
    collection do
      put 'refresh_count', 'color_update', 'generate', 'upload_ins'
      get 'color', 'reimport', 'to_generate', 'instruction'
    end

    member do
      put 'make_current'
    end

    resources :reports, :only => [] do
      collection do
        get 'count_varience', 'count_frozen', 'tags', 'inventories', 'remote_warehouse_by_item', 'remote_warehouse_by_warehouse'
      end
    end
  end

  namespace :audit do
    resources :tags
  end

  namespace :dataentry do
    resources :inventories
    resources :items do
      resources :inventories
    end
  end

  namespace :god do
    resources :rechecks

    resources :checks do
      resources :activities
      resources :tags
      resources :inventories
      
      collection do
        get 'current', 'history', 'import_cost'
        put 'do_import_cost'
      end

      put 'change_state', :on => :member
    end
  end

  namespace :adm do
    resources :wait_prints do
      get 'multiple_create', :on => :collection
    end

    resources :items do
      resources :tags

      get 'missing_cost', :on => :collection

      member do
        get 'input_price'
        put 'update_price'
      end
    end

    resources :tags do
      get 'adj_list', :on => :collection

      member do
        get 'to_adj'
        put 'update_adj'
      end
    end

    resources :counters

    resources :items do
      resources :inventories, :only => [:new, :create]
    end

    resources :inventories do
      resources :tags
    end

    resources :counts do
      get 'missing_tag', 'result', :on => :collection
    end

    resources :locations do
      resources :assigns
    end
  end

  root :to => "dashboards#show"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  scope :raw_in_chk, lambda { |check_id| includes(:inventory => {:location => :check}).where(:checks => {:id => check_id}) }
  scope :countable, includes(:inventory => :location).where(:locations => {:is_remote => false}).where(:state.not_eq % "deleted" | :state.eq % nil)
  scope :in_check, lambda { |check_id| raw_in_chk(check_id).countable }
  scope :not_finish, lambda{|count| where("count_#{count}".to_sym.eq % nil).countable}
  scope :finish, lambda{|count| where("count_#{count}".to_sym.not_eq % nil).countable}
  scope :deleted_s, where(:state => "deleted")
  scope :ready_to_print, where(:wait_for_print => true).countable

  belongs_to :inventory

  search_methods :counted_by
  scope :counted_by, lambda { |counter_count|
    counter = Counter.find(counter_count.split('_').first)
    count = counter_count.split('_').last.to_i
    
    includes(:inventory => :location).where(:locations => {:id => counter.assigns.where(:count => count).map(&:location).map(&:id)})
  }

  search_methods :tolerance_q
  scope :tolerance_q, lambda { |quantity|
    where("abs((tags.count_1 - tags.count_2) / least(cast(tags.count_1 as float), cast(tags.count_2 as float))) * 100 > ? and least(cast(tags.count_1 as float), cast(tags.count_2 as float)) <> 0",
    quantity.to_f.abs).countable
  }

  search_methods :tolerance_v
  scope :tolerance_v, lambda {|value| includes(:inventory => :item).where(["abs(tags.count_1 * items.cost - tags.count_2 * items.cost) > ?", value.to_f.abs]).countable}

  scope :tole_q_or_v, lambda {|quantity, value| includes(:inventory => :item) \
    .where("(least(cast(tags.count_1 as float), cast(tags.count_2 as float)) <> 0 and abs((tags.count_1 - tags.count_2) / least(cast(tags.count_1 as float), cast(tags.count_2 as float))) * 100 >= ?) or (abs(tags.count_1 * items.cost - tags.count_2 * items.cost) >= ?)", 
      (quantity || 0).to_f.abs, (value || 0).to_f.abs).countable}


  after_save :launch_inv_save
  after_destroy :launch_inv_save_with_out_reload
  def launch_inv_save
    self.inventory.try(:save)
    self.reload
  end
  
  def launch_inv_save_with_out_reload
    self.inventory.try(:save)
  end

  attr_accessor :location_id, :item_id
  before_save :adj_inventory
  def adj_inventory
    if @location_id && @item_id
      chk = Location.find(@location_id).check

      return if Item.find(@item_id).item_group.check != chk

      inv = Inventory.in_check(chk.id).where(:location_id.eq % @location_id & :item_id.eq % @item_id).first
      if inv
        self.inventory = inv
      else
        self.inventory = Inventory.create(
          :item => Item.find(@item_id),
          :location => Location.find(@location_id)
        )
      end
    end
  end

  before_save :adj_final_count
  def adj_final_count
    if !self.adjustment.nil?
      self.final_count = self.adjustment
    elsif self.count_1.nil? || self.count_2.nil?
      self.final_count = nil
    elsif self.count_1 == self.count_2 && self.count_3.nil?
      self.final_count = self.count_1
    else
      self.final_count = self.count_3.nil? ? [self.count_1, self.count_2].min : self.count_3
    end
  end
  
  def counted_value
    return nil if final_count.nil? || self.inventory.item.try(:cost).nil?
    final_count * self.inventory.item.try(:cost)
  end
  
  def count_differ
    return 0 if self.count_2.nil? || self.count_1.nil?

    bas = [self.count_1, self.count_2].min
    return 0 if bas == 0

    return (((count_2 - count_1).to_f / bas.to_f).abs * 100).to_f.round(3).abs if bas > 0
  end

  def value_1
    ((self.count_1 || 0) * (self.inventory.item.try(:cost) || 0)).round(3)
  end
  
  def value_2
    ((self.count_2 || 0) * (self.inventory.item.try(:cost) || 0)).round(3)
  end

  def value_differ
    return nil if self.count_2.nil? || self.count_1.nil? || self.inventory.item.try(:cost).nil? || self.inventory.item.try(:cost) == 0

    return ((self.count_2 - self.count_1) * self.inventory.item.try(:cost)).round(3).abs
  end
end











# == Schema Information
#
# Table name: tags
#
#  id             :integer         not null, primary key
#  count_1        :integer
#  count_2        :integer
#  count_3        :integer
#  created_at     :datetime
#  updated_at     :datetime
#  inventory_id   :integer
#  sloc           :string(255)
#  final_count    :integer
#  state          :string(255)
#  adjustment     :integer
#  audit          :integer
#  wait_for_print :boolean         default(TRUE)
#  printed_time   :integer         default(0)
#

app/controllers/adm/tags_controller.rb
require 'ext/tag_table'

class Adm::TagsController < Adm::BaseController
  layout "tags"

  # GET /tags
  # GET /tags.xml
  def index    
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])

    respond_to do |format|
      format.html { @tags = @search.paginate(:page => params[:page]) }

      format.pdf {
        @tags = @search.all

        pdf = Prawn::Document.generate_tags @tags
        send_data pdf.render, :filename => "tickets.pdf", :disposition => 'attachment'
      }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    if params[:inventory_id]
      inventory = Inventory.find(params[:inventory_id])
      @tag.item_id, @item = inventory.item.id, inventory.item
      @tag.location_id = inventory.location.id
    elsif params[:item_id]
      @tag.item_id, @item = params[:item_id].to_i, Item.find(params[:item_id])
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @item = @tag.inventory.item
    @tag.item_id = @item.id
    @tag.location_id = @tag.inventory.location.id
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to adm_tags_path, :notice => "Ticket No.#{@tag.id} was successfully created." }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])
    
    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to( adm_tag_path(@tag), :notice => 'Ticket was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @tag.update_attributes(:state => "deleted")

    respond_to do |format|
      format.html { redirect_to(adm_tags_url, :notice => "Deleted successfully.") }
      format.xml  { head :ok }
    end
  end

  def adj_list
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])
    @tags = @search.paginate(:page => params[:page])
  end

  def to_adj
    @check = curr_check

    @tag = Tag.in_check(@check.id).find(params[:id])
  end

  def update_adj
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    
    if @tag.update_attributes(:adjustment => (params[:tag] || {})[:adjustment])
      redirect_to adj_list_adm_tags_path, :notice => "Updated."
    else
      render :adj_list
    end
  end

end

app/controllers/audit/tags_controller.rb
require 'ext/spreadsheet'

class Audit::TagsController < Audit::BaseController
  before_filter do
    @nav = :audit
  end

  def edit
    @tag = Tag.in_check(curr_check.id).countable.find(params[:id])
  end

  def index
    @search = Tag.in_check(curr_check.id).countable.includes(:inventory => :item, :inventory => :location).search(params[:search])
    @tags = @search.paginate(:page => params[:page])
  end
  
  def update
    @tag = Tag.in_check(curr_check.id).countable.find(params[:id])
    
    if @tag.update_attributes(params[:tag])
      redirect_to audit_tags_path, :notice => "Audit updated."
    else
      render :edit
    end
  end
end

app/controllers/god/tags_controller.rb
require 'ext/spreadsheet'

class God::TagsController < God::BaseController

  before_filter do
    @nav = @check.current ? :control : :archive
  end

  def index

  end
  
end

app/controllers/tags_controller.rb
require 'ext/tag_table'

class TagsController < ApplicationController
  layout "settings"

  # GET /tags
  # GET /tags.xml
  def index    
    @search = Tag.in_check(curr_check.id).includes(:inventory => :item, :inventory => :location).search(params[:search])

    respond_to do |format|
      format.html { @tags = @search.paginate(:page => params[:page]) }

      format.pdf {
        @tags = @search.all

        pdf = Prawn::Document.generate_tags @tags
        send_data pdf.render, :filename => "tags.pdf", :disposition => 'attachment'
      }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    if params[:inventory_id]
      inventory = Inventory.find(params[:inventory_id])
      @tag.item_id, @item = inventory.item.id, inventory.item
      @tag.location_id = inventory.location.id
    elsif params[:item_id]
      @tag.item_id, @item = params[:item_id].to_i, Item.find(params[:item_id])
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @item = @tag.inventory.item
    @tag.item_id = @item.id
    @tag.location_id = @tag.inventory.location.id
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])
    
    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.in_check(curr_check.id).find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => {:class => 'uniform'} do |f| %>
	<% if @tag.errors.any? %>
		<div class="error msg">
			<h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
			<ul>
			<% @tag.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
			</ul>
		</div>	
	<% end %>

	<fieldset>
		<legend>Choose Location</legend>
		<dl class="inline">
			<dt><%= f.label :item_id, 'Item Number' %></dt>
			<dd>
				<%= f.label :item_id, @item.code %>
				<%= f.hidden_field :item_id %>
			</dd>
			<dt><%= f.label :item_description %></dt>
			<dd>
				<%= f.label :item_description, @item.description %>
			</dd>
			<dt><%= f.label :location_id, 'Location' %></dt>
			<dd>
				<%= f.collection_select(:location_id, curr_check.locations, :id, :code, {:include_blank => false}, {:class => "small", :tabindex => 1})  %>
			</dd>
			<dt><%= f.label :sloc, 'Shelf Location' %></dt>
			<dd><%= f.text_field :sloc, :tabindex => 2, :class => 'small' %></dd>
		</dl>
	</fieldset>
	<div class="buttons">
		<%= f.submit :class => 'button' %>
	</div>

<% end %>

app/views/tags/_row.html.erb
<% if defined?(show_header) && show_header %>
<tr>
	<th>Tag #</th>
	<th>Shelf Loc.</th>
	<th class='number'>Count 1</th>
	<th class='number'>Count 2</th>
	<th class='number'>Count 3</th>
	<th class='number'>Final Adj.</th>
	<th class='number'>Audit</th>
	<th class='number'>Final Qty</th>
</tr>
<% end %>
<tr>
	<td><%= tag.id %></td>
	<td><%= tag.sloc %></td>
	<td class='number'><%= tag.count_1 %></td>
	<td class='number'><%= tag.count_2 %></td>
	<td class='number'><%= tag.count_3 %></td>
	<td class='number'><%= tag.adjustment %></td>
	<td class='number'><%= tag.audit %></td>
	<td class='number'><%= tag.final_count %></td>
</tr>

app/views/tags/_search_dl.html.erb
<% bg_ind = defined?(tab_index) ? tab_index : 1 %>

<dt>
<%= f.label :inventory_item_code_like, 'Item #' %>
</dt>
<dd>
<%= f.text_field :inventory_item_code_like, :class => "small", :tabindex => bg_ind + 1 %>

<% if allow_data_entry? %>
<% @item = curr_check.items.where(:code.eq => params[:search][:inventory_item_code_like]).first if params[:search] && params[:search][:inventory_item_code_like] %>

<% if @item %>
	<%= link_to "Create New Ticket with this Item # #{@item.code}", new_adm_item_tag_path(@item) %>
<% else %>
	<% @new_item_params = (params[:search] && params[:search][:inventory_item_code_like]) ? {:item => {:code => params[:search][:inventory_item_code_like]}} : {} %>
	<%= link_to "Item not found! Click here to create new item # #{params[:search][:inventory_item_code_like]}", new_adm_item_path(({:sub_menu => @sub_menu}).merge @new_item_params) if params[:search] && !params[:search][:inventory_item_code_like].blank? %>
<% end %>
<% end %>

</dd>

<dt><%= f.label :inventory_location_id_eq, 'Warehouse' %></dt>
<dd>
	<%= f.collection_select(:inventory_location_id_eq, check.locations.tagable, :id, :code, {:include_blank => true}, {:class => "small", :tabindex => bg_ind + 2})  %>
</dd>

<dt><%= f.label :id_eq, 'Ticket #' %></dt>
<dd><%= f.text_field :id_eq, :class => "small", :tabindex => bg_ind + 3 %></dd>

<dt><%= f.label :id_gte, 'Ticket # range' %></dt>
<dd>
	<%= f.text_field :id_gte, :class => "small", :tabindex => bg_ind + 4 %> -
	<%= f.text_field :id_lte, :class => "small", :tabindex => bg_ind + 5 %>
</dd>


<!--dt><%= f.label :counted_by %></dt>
<dd>
	 f.select(:counted_by, Counter.counted_bys, { :include_blank => true }, {:class => "small", :tabindex => bg_ind + 5})
</dd-->

app/views/tags/index.html.erb
<% @sub_menu = :tag %>

<article>
	<%= render :partial => 'shared/flash' %>
	<%= form_for @search do |f| %>
		<fieldset>
			<legend>Search</legend>
			<dl class="inline">
				<%= render :partial => 'tags/search_dl', :locals => {:f => f} %>
			</dl>
			<div class="buttons">
				<%= f.submit 'Search', :class => "button" %>
			</div>
		</fieldset>
	<% end %>
</article>

<article>
	<h1>All Tags</h1>
	<%= loading_link 'Print Result', url_for(request.params.merge(:format => :pdf)), :class => 'button' %>

	<table class="gtable detailtable">
		<thead>
			<tr>
				<th><%= sort_link @search, :id, 'Tag' %></th>
				<th><%= sort_link @search, :inventory_item_code, 'Item' %></th>
				<th><%= sort_link @search, :inventory_location_code, 'Location' %></th>
				<th><%= sort_link @search, :inventory_item_cost, 'Cost' %></th>
				<th><%= sort_link @search, :sloc, 'Shelf Loc' %></th>
				<th>Action</th>
			</tr>
		</thead>
		
		<tbody>
			<% @tags.each do |tag| %>
			<% next unless tag.inventory %>
			<tr>
				<td><%= tag.id %></td>
				<td><%= tag.inventory.item.try(:code) %> <a href="#" class="detail-link">more</a></td>
				<td><%= tag.inventory.location.try(:code) %></td>
				<td class='number'><%=number_to_currency (tag.inventory.item.try(:cost) || 0) %></td>
				<td><%= tag.sloc %></td>
				<td>
					<% if curr_check.state == 'open' %>
					<%= link_to image_tag('icons/edit.png'), edit_tag_path(tag), :title => 'Edit' %>
					<%= link_to image_tag('icons/cross.png'), tag_path(tag), :method => :delete, :confirm => "Are you sure to delete Tag #{tag.id}?", :title => 'Delete' %>
					<% end %>
					<%= link_to image_tag('icons/printer.png'), tags_path(:search => {:id_eq => tag.id}, :format => :pdf), :title => 'Print' %>
				</td>
			</tr>
			<tr class="detail">
				<td colspan="6">
					<table>
						<tbody>
							<tr>
								<td><%= tag.inventory.item.try(:description) %></td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<% end %>

		</tbody>
	</table>
	
	<div class="tablefooter clearfix">
		<%= will_paginate @tags %>
	</div>
</article>

app/views/tags/show.html.erb
<% @sub_menu = :tags %>
<article>

<table class="infos">
	<tr>
		<th>Tag Number</th>
		<td><%= @tag.id %></td>
	</tr>
	<tr>
		<th>Item Number</th>
		<td><%= @tag.inventory.item.try(:code) %></td>
	</tr>
	<tr>
		<th>Description</th>
		<td><%= @tag.inventory.item.try(:description) %></td>
	</tr>
	<tr>
		<th>Location</th>
		<td><%= @tag.inventory.location.try(:code) %></td>
	</tr>
	<tr>
		<th>Shelf Location</th>
		<td><%= @tag.try(:sloc) %></td>
	</tr>
	<tr>
		<th>Date</th>
		<td><%= @tag.created_at.to_date %></td>
	</tr>
</table>

<div class="tablefooter clearfix">
	<div class="actions">
	<%= link_to image_tag('icons/printer.png'), tags_path(:search => {:id_eq => @tag.id}, :format => :pdf) %>
	</div>
</div>
</article>

app/views/tags/to_import.html.erb
<% @sub_menu = :import %>
<article>
	<h1>Import from All Order</h1>

	<%= form_tag import_tags_path, :method => :post, :class => 'uniform', :multipart => true do %>
	<fieldset>
		<legend>Form</legend>
		<dl class="inline">
			<dt><label for="upload">Excel/CSV</label></dt>
			<dd><%= file_field_tag :file %></dd>
		</dl>
		<div class="buttons">
			<%= submit_tag 'Import', :class => 'button' %>
		</div>
	</fieldset>
	<% end %>
</article>