config/routes.rb
Scs::Application.routes.draw do

  devise_for :gods

  devise_for :admins

  resources :accounts

  resources :all_orders, :only => [] do
    collection do
      post 'generate'
    end
  end

  resources :attachments do
    member do
      get 'download'
    end
  end

  resources :locations

  resources :settings

  resources :counts

  resources :checks do
    collection do
      put 'refresh_count', 'color_update', 'generate', 'upload_ins'
      get 'color', 'reimport', 'to_generate', 'instruction'
    end

    member do
      put 'make_current'
    end

    resources :reports, :only => [] do
      collection do
        get 'count_varience', 'count_frozen', 'tags', 'inventories', 'remote_warehouse_by_item', 'remote_warehouse_by_warehouse'
      end
    end
  end

  namespace :audit do
    resources :tags
  end

  namespace :dataentry do
    resources :inventories
    resources :items do
      resources :inventories
    end
  end

  namespace :god do
    resources :rechecks

    resources :checks do
      resources :activities
      resources :tags
      resources :inventories
      
      collection do
        get 'current', 'history', 'import_cost'
        put 'do_import_cost'
      end

      put 'change_state', :on => :member
    end
  end

  namespace :adm do
    resources :wait_prints do
      get 'multiple_create', :on => :collection
    end

    resources :items do
      resources :tags

      get 'missing_cost', :on => :collection

      member do
        get 'input_price'
        put 'update_price'
      end
    end

    resources :tags do
      get 'adj_list', :on => :collection

      member do
        get 'to_adj'
        put 'update_adj'
      end
    end

    resources :counters

    resources :items do
      resources :inventories, :only => [:new, :create]
    end

    resources :inventories do
      resources :tags
    end

    resources :counts do
      get 'missing_tag', 'result', :on => :collection
    end

    resources :locations do
      resources :assigns
    end
  end

  root :to => "dashboards#show"

end

app/models/god.rb
class God < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :trackable, :validatable, :timeoutable
  #  :recoverable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
end

# == Schema Information
#
# Table name: gods
#
#  id                   :integer         not null, primary key
#  email                :string(255)     default(""), not null
#  encrypted_password   :string(128)     default(""), not null
#  password_salt        :string(255)     default(""), not null
#  reset_password_token :string(255)
#  remember_token       :string(255)
#  remember_created_at  :datetime
#  sign_in_count        :integer         default(0)
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  current_sign_in_ip   :string(255)
#  last_sign_in_ip      :string(255)
#  username             :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#

app/controllers/checks_controller.rb
class ChecksController < BaseController

  before_filter do
    @nav = :control
  end

  # GET /checks
  # GET /checks.xml
  def index
    @checks = Check.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @checks }
    end
  end

  # GET /checks/1
  # GET /checks/1.xml
  def show
    @check = Check.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @check }
    end
  end

  def current
    @check = Check.curr_s.first
  end

  # GET /checks/new
  # GET /checks/new.xml
  def new
    @check = Check.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @check }
    end
  end

  # GET /checks/1/edit
  def edit
    @check = Check.find(params[:id])
  end

  # POST /checks
  # POST /checks.xml
  def create
    @check = Check.new(params[:check])

    @check.admin = current_admin
    if @check.save && @check.make_current!
      redirect_to(current_god_checks_path, :notice => 'Check was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /checks/1
  # PUT /checks/1.xml
  # reimport
  def update
    @check = Check.find(params[:id])
    @check.attributes = params[:check]

    require "pp"
    pp params[:check]

    respond_to do |format|
      if @check.switch_inv!(@check.import_time + 1)
        format.html { redirect_to(current_god_checks_path, :notice => 'Reimport finished.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "reimport" }
        format.xml  { render :xml => @check.errors, :status => :unprocessable_entity }
      end
    end
  end

  def reimport
    @check = curr_check
    @check.attributes = params[:check]
  end

  # DELETE /checks/1
  # DELETE /checks/1.xml
  def destroy
    @check = Check.find(params[:id])
    @check.destroy

    respond_to do |format|
      format.html { redirect_to(checks_url) }
      format.xml  { head :ok }
    end
  end

  def make_current
    @check = Check.find(params[:id])
    if @check.make_current!
      redirect_to current_checks_path, :notice => "CURREN CHECK has been changed to #{@check.description || @check.id}."
    else
      render index
    end
  end

  def refresh_count
    curr_check.cache_counted!
    
    redirect_to missing_cost_items_path, :notice => "Refresh finished."
  end

  def color
    @check = curr_check
  end

  def color_update
    if curr_check.update_attributes(params[:check])
      redirect_to color_checks_path, :notice => "Colors changed."
    else
      render :color
    end
  end

  def generate
    curr_check.generate!
    redirect_to current_checks_path, :notice => "Initial tags have been generated."
  end

  def to_generate
  end

  def instruction
    @check = curr_check
  end

  def upload_ins
    @check = curr_check
    
    @check.update_attributes(:instruction_file => params[:check][:instruction_file]) unless params[:check].blank? || params[:check][:instruction_file].blank?
    
    redirect_to instruction_checks_path, :notice => "Uploaded successfully."
  end

end

app/controllers/god/activities_controller.rb
class God::ActivitiesController < God::BaseController
  before_filter do
    @check = Check.find(params[:check_id])
    @nav = (@check == curr_check ? :control : :archive)
  end
  
  def index
    @search = @check.activities.valid_s.search(params[:search])
    @activities = @search.order("created_at DESC").paginate(:page => params[:page])
  end
end

app/controllers/god/base_controller.rb
class God::BaseController < ApplicationController
  before_filter {check_role [:controller, :mgt]}
end

app/controllers/god/checks_controller.rb
class God::ChecksController < God::BaseController
  layout :choose_lay

  before_filter do
    if ["current", "new"].include?(params["action"])
      @nav = :control
    else
      @nav = :archive
    end
  end

  # Status page
  def current
    if Check.curr_s.where(:state => 'init').count > 0
      redirect_to new_god_check_path(:step => 2)
      return
    end

    @check = Check.opt_s.first
  end

  # Create New Check
  before_filter :only => [:new, :create] do
    @step = (params[:step] || 1).to_i
  end
  def new
    @check = @step == 1 ? Check.new : Check.curr_s.first
    render "new_#{@step}"
  end

  def create
    if send "create_step_#{@step}"
      if @step < 2
        redirect_to new_god_check_path(:step => (@step + 1))
      else
        redirect_to edit_god_check_path(curr_check), :notice => "Check created. Please setup the check."
      end
    else
      render "new_#{@step}"
    end
  end

  # Setting page
  def edit
    @check = curr_check
  end

  # Setting page
  def update
    if curr_check.update_attributes(params[:check])
      redirect_to edit_god_check_path(curr_check.reload), :notice => "Basic Setting updated."
    else
      render :edit
    end
  end

  def change_state
    curr_check.state = params[:state]
    curr_check.generate_xls if curr_check.state == 'complete'
    curr_check.archive! if curr_check.state == 'archive'

    if curr_check.save
      redirect_to current_god_checks_path, :notice => "CURREN CHECK has been changed to #{params[:state]}."
    else
      redirect_to current_god_checks_path, :notice => "Failed change to #{params[:state]}."
    end
  end

  def history
    @checks = Check.history.paginate(:page => params[:page])
  end

  def import_cost
    @nav = :control
    @check = curr_check
  end

  def do_import_cost
    @nav = :control
    @check = curr_check

    if @check.update_attributes(params[:check])
      redirect_to current_god_checks_path, :notice => 'Cost import finish.'
    else
      render :import_cost
    end
  end

  private
  def create_step_1
    @check = Check.new(params[:check])
    @check.save && @check.make_current! && @check.refresh_location
  end

  def create_step_2
    @check = Check.curr_s.first
    
    @check.set_onsite_locations(params["onsite_ids"])
    
    @check.refresh_item_and_group && @check.refresh_inventories && @check.reload.update_attributes(:state => "open", :admin => current_admin) && @check.generate!
  end
  
  def choose_lay
    params[:action] == 'edit' ? 'settings' : 'application'
  end

end

app/controllers/god/inventories_controller.rb
require 'ext/spreadsheet'

class God::InventoriesController < God::BaseController

  before_filter do
    @check = Check.find(params[:check_id])
    @nav = @check.current ? :control : :archive
  end

  def index
 
  end
  
end

app/controllers/god/rechecks_controller.rb
class God::RechecksController < God::BaseController
  before_filter do
    @nav = :control
  end

  def edit
    @check = curr_check
  end

  def update
    @check = curr_check

    if @check.update_attributes(params[:check])
      redirect_to god_rechecks_path, :notice => "Re-check data imported."
    else
      render :edit
    end
  end

  def index
    @check = curr_check
    @search = Inventory.in_check(@check.id).where(:re_export_offset.not_eq => 0).search(params[:search])

    respond_to do |format|
      format.html { @inventories = @search.paginate(:page => params[:page]) }
      format.xls {
        @inventories = @search.all
        book = Spreadsheet::Workbook.new
        
        data = book.generate_xls(
        "Re-check", @inventories,        
        %w{Warehouse Part# Desc. Frozen_QTY Final_SCS_QTY Adjustment_to_QTY_frozen Re_Export_Qty Re_Export_offset},
        [[:location, :code], 
          [:item, :code],
          [:item, :description],
          :quantity,
          :result_qty,
          :ao_adj,
          :re_export_qty,
          :re_export_offset]
        )

        send_data data, :filename => "Re-check_#{@check.description}.xls", :disposition => 'attachment'
      }
    end
  end
end

app/controllers/god/tags_controller.rb
require 'ext/spreadsheet'

class God::TagsController < God::BaseController

  before_filter do
    @nav = @check.current ? :control : :archive
  end

  def index

  end
  
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/god/checks/current.html.erb
<% @sub_menu = :current %>

<% if allow_check_control? %>
<article>
	<%= render :partial => "shared/flash" %>
	<h1>Status</h1>

	<h2>Actions</h2>

	<div class="actions">
		
		<% if has_curr_check? %>
		<table class='infos'>

			<tr>
				<td>
					<%= action_link (curr_check.state == 'open'), 'Re-import Cost', import_cost_god_checks_path, :class => "button" %>
				</td>
				<td>
					<%= "(You can not reimport cost now.)" unless (curr_check.state == 'open') %> Import latest AO cost into SCS. <strong>(Items.xls)</strong>
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link (curr_check.state == 'open'), 'Re-import Qty', reimport_checks_path, :class => "button" %>
				</td>
				<td>
					<%= "(You can not reimport qty now.)" unless (curr_check.state == 'open' && !curr_check.final_inv) %> Re-import frozen quantities from ALL ORDER to SCS. <strong>(Inventory.xls)</strong>
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link (curr_check.state == 'open' && !curr_check.final_inv), 'Re-import Qty (Final)', reimport_checks_path(:check => {:final_inv => true}), :class => "button orange" %>
				</td>
				<td style="color:red; font-weight:bold">
					<%= "(You can not do the Final Re-Import Qty now.)" unless (curr_check.state == 'open' && !curr_check.final_inv) %> IMPORTANT: One time only, imported quantities should be final. <strong>(Inventory.xls)</strong>
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link curr_check.can_complete?, 'Complete', change_state_god_check_path(curr_check, :state => :complete), :method => :put, :confirm => "Are you sure to complete the check '#{curr_check.description}' ?", :class => "button" %>
				</td>
				<td>
					<%= "(You can not complete the check now.)" unless curr_check.can_complete? %> Complete the whole stock check. Generate adjustment excels.
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link curr_check.state == 'open', 'Cancel', change_state_god_check_path(curr_check, :state => :cancel), :method => :put, :confirm => "Are you sure to cancel the check '#{curr_check.description}' ?", :class => "button" %>
				</td>
				<td>
					<%= "(You can not cancel the check now.)" unless curr_check.state == 'open' %> Cancel current stock check session.
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link (curr_check.state == 'complete'), 'Recheck', god_rechecks_path, :class => 'button' %>
				</td>
				<td>
					<%= "(You can not Recheck the check now.)" unless (curr_check.state == 'complete') %> You must complete the stock check first and export all adjustment excels back to ALL ORDER.
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link ['complete', 'cancel'].include?(curr_check.state), 'Archive', change_state_god_check_path(curr_check, :state => :archive), :method => :put, :confirm => "Are you sure to archive the check '#{curr_check.description}' ?", :class => "button" %>
				</td>
				<td>
					<%= "(You can not archive the check now.)" unless (['complete', 'cancel'].include?(curr_check.state)) %> Archive the stock check.
				</td>
			</tr>

			<tr>
				<td>
					<%= action_link (curr_check.state != 'open'), 'Reopen', change_state_god_check_path(curr_check, :state => :open), :method => :put, :confirm => "Are you sure to reopen the check '#{curr_check.description}' ?", :class => "button" %>
				</td>
				<td>
					<%= "(You can not reopen the check now.)" unless (curr_check.state != 'open') %> Reopen a completed or canceled stock check in the case you might forget to input some tickets.
				</td>
			</tr>
		</table>
		<% end %>

		<% unless has_curr_check? %>
			<%= link_to 'Start A Stock Check', new_god_check_path, :class => "button" %>
			<%= link_to 'Accounts', accounts_path, :class => "button" %>
		<% end %>
	</div>
</article>
<% end %>

<% if has_curr_check? %>
<article>
<h2>Common</h2>
<%= render :partial => 'shared/curr_check', :locals => {:curr_check => @check} %>
</article>

<article>
<h2>Log</h2>
<table class="infos">
	<tr>
		<td><%= link_to 'Log', god_check_activities_path(curr_check) %></td>
	</tr>
</table>
</article>

<% if curr_check.state == 'complete' %>
<article>
	<h2>Download</h2>

	<table class="infos">
	<tbody>
		<tr>
			<th>Export to ALL ORDER</th>
			<td>
			<%= link_to('inventory_adjustment.xls', download_attachment_path(curr_check.inv_adj_xls)) unless curr_check.inv_adj_xls.nil? %>
			</td>
		</tr>
		<tr>
			<th>Manual Input XLS</th>
			<td><%= link_to('manual_input.xls', download_attachment_path(curr_check.manual_adj_xls)) unless curr_check.manual_adj_xls.nil? %></td>
		</tr>
	</tbody>
	</table>
</article>
<% end %>
<% end %>

app/views/god/checks/edit.html.erb
<% @sub_menu = :basic %>

<% content_for :head do %>
<%= javascript_include_tag 'jscolor/jscolor.js' %>

<script>
	jQuery(function($) {
		$('#edit_ao_adjust_acc_link').bind('click', function(evn){
			$(this).prev().hide();
			$(this).prev().prev().show();
			$(this).hide();
			evn.preventDefault();
		});
	});
</script>
<% end %>

<article>
	<%= render :partial => 'shared/flash' %>
	<h1>Basic Setting</h1>
	
	<%= form_for @check, :url => god_check_path(@check), :html => {:class => 'uniform', :multipart => true} do |f| %>
		<fieldset>
			<legend>Common</legend>
			<dl class="inline">
				<dt><%= f.label :description, "Inventory Name" %></dt>
				<dd><%= f.text_field :description, :tabindex => 1 %></dd>
				
				<dt><%= f.label :start_time, "Start Date" %></dt>
				<dd><%= f.text_field :start_time, :class => "need_date", :tabindex => 2 %>
				</dd>
			</dl>
		</fieldset>
		
		<fieldset>
			<legend>Third Count Criteria</legend>
			<dl class="inline">
				<dt><%= f.label :credit_v, "Value ($)" %></dt>
				<dd><%= f.text_field :credit_v, :tabindex => 3 %></dd>
				
				<dt><%= f.label :credit_q, "Qty (%)" %></dt>
				<dd><%= f.text_field :credit_q, :tabindex => 4 %></dd>
			</dl>
		</fieldset>

		<fieldset>
			<legend>Set Colors</legend>
			<dl class="inline">
				<dt><%= f.label :color_1 %></dt>
				<dd><%= f.text_field :color_1, :tabindex => 1, :class => 'color', :tabindex => 5 %></dd>

				<dt><%= f.label :color_2 %></dt>
				<dd><%= f.text_field :color_2, :tabindex => 2, :class => 'color', :tabindex => 6 %></dd>

				<dt><%= f.label :color_3 %></dt>
				<dd>
					<%= f.text_field :color_3, :tabindex => 3, :class => 'color', :tabindex => 7 %>
				</dd>

			</dl>
		</fieldset>

		<fieldset>
		<legend>Instruction Excel</legend>

		<dl class='inline'>
			<dt><%= f.label :instruction_file, 'Instruction 1' %></dt>
			<dd>
				<%= f.file_field :instruction_file, :tabindex => 8 %>
			</dd>
			
			<dt><%= f.label :instruction2_file, 'Instruction 2' %></dt>
			<dd>
				<%= f.file_field :instruction2_file, :tabindex => 8 %>
			</dd>
			<dt><%= f.label :instruction3_file, 'Instruction 3' %></dt>

			<dd>
				<%= f.file_field :instruction3_file, :tabindex => 8 %>
			</dd>

			<dt><%= f.label :instruction4_file, 'Instruction 4' %></dt>
			<dd>
				<%= f.file_field :instruction4_file, :tabindex => 8 %>
			</dd>
			
		</dl>
		</fieldset>
		
		<fieldset>
		<legend>All Order Adjustment Account</legend>

		<dl class='inline'>
			<dt><%= f.label :ao_adjust_acc, 'AO Adjustment Account' %></dt>
			<dd>
				<%= f.text_field :ao_adjust_acc, :tabindex => 9, :style => 'display:none' %>
				<span><%= @check.ao_adjust_acc %></span>
				<a href='#' id='edit_ao_adjust_acc_link'><%= image_tag 'icons/edit.png' %></a>
				<small>This is used for exporting the adjustment files back to All Order.</small>
			</dd>
		</dl>
		</fieldset>
		
		
		<%= f.submit 'Save', :class => 'button' %>
	<% end %>
</article>

app/views/god/checks/history.html.erb
<article>
	<h1>Archived List</h1>

	<table class="gtable">
		<thead>
		<tr>
			<th>Inventory Name</th>
			<th>Started at</th>
			<th>Launched by</th>
			<th>Final</th>
		</tr>
		</thead>
		
		<tbody>
		<% Check.history.each do |check| %>
		<tr>
			<td><%= check.description %></td>
			<td><%=l check.created_at, :format => :long %></td>
			<td><%= check.admin.try(:username) %></td>
			<td>
				<%= link_to "Variance Count 1 VS 2", count_varience_check_reports_path(check, :nav => :archive) %>
				<br />
				<%= link_to "Count Result VS Frozen QTY", count_frozen_check_reports_path(check, :nav => :archive) %>
				<br />
				<%= link_to "Final - Summary of counts by location", tags_check_reports_path(check, :nav => :archive) %>
				<br />
				<%= link_to "Final - Summary of counts by value", inventories_check_reports_path(check, :nav => :archive) %>
				<br />
				<%= link_to "Log", god_check_activities_path(check) %>
				
			</td>
		</tr>
		<% end %>
		</tbody>
	</table>

</article>

app/views/god/checks/import_cost.html.erb
<article>
	<h1>Re-import Cost</h1>
	
	<%= render :partial => 'shared/errors', :locals => {:object => @check} %>
	
	<%= form_for @check, :url => do_import_cost_god_checks_path, :html => {:class => 'uniform', :multipart => true} do |f| %>
		<fieldset>
		<legend>Item excel</legend>
		<dl class='inline'>

			<dt><%= f.label :description, 'Inventory Name' %></dt>
			<dd><%= @check.description %></dd>

			<dt><%= f.label :reimport_cost_xls, "Items.xls" %></dt>
			<dd>
				<%= f.file_field :reimport_cost_xls %>
				<small>Import latest AO Cost into SCS</small>
				<small>ALL ORDER: Reports -> Items -> Items</small>
			</dd>

		</dl>
		</fieldset>

		<div class="buttons">
			<%= loading_submit f, "Re import", :class => 'button' %>
		</div>
	<% end %>
</article>

app/views/god/checks/new_1.html.erb
<% @sub_menu = :current %>
<article>
	<h1>New check Step 1</h1>
	
	<%= render :partial => 'shared/errors', :locals => {:object => @check} %>

	<%= form_for @check, :url => god_checks_path, :html => {:class => 'uniform', :multipart => true} do |f| %>
		<%= hidden_field_tag :step, @step %>

		<fieldset>
		<legend>Upload Locations / PartNumbers / Inventories</legend>
		<dl class='inline'>

			<dt><%= f.label :description, 'Inventory Name' %></dt>
			<dd>
			<%= f.text_field :description, :tabindex => 1 %>
			</dd>
		
			<dt><%= f.label :locations_xls %></dt>
			<dd>
				<%= f.file_field :locations_xls, :tabindex => 2 %>
				<small>ALL ORDER: Reports -> Lists -> Location list</small>
			</dd>
		
			<dt><%= f.label :item_groups_xls %></dt>
			<dd>
				<%= f.file_field :item_groups_xls, :tabindex => 3 %>
				<small>ALL ORDER: Reports -> Lists -> Item Groups</small>
			</dd>

			<dt><%= f.label :items_xls %></dt>
			<dd>
				<%= f.file_field :items_xls, :tabindex => 4 %>
				<small>ALL ORDER: Reports -> Items -> Items</small>
			</dd>

			<dt><%= f.label :inventories_xls %></dt>
			<dd>
				<%= f.file_field :inventories_xls, :tabindex => 5 %>
				<small>ALL ORDER: Reports -> Inventory Tracking -> Location by Item Summary</small>
			</dd>

		</dl>
		</fieldset>

		<div class="buttons">
			<%= loading_submit f, "Next", :class => 'button' %>
		</div>
		
	<% end %>
	
	
</article>

app/views/god/checks/new_2.html.erb
<% @sub_menu = :current %>
<article>
	<h1>New check step 2</h1>

	<%= render :partial => 'shared/errors', :locals => {:object => @check} %>

	<%= form_for Check.new, :url => god_checks_path, :html => {:class => 'uniform'} do |f| %>
		<%= hidden_field_tag :step, @step %>
		<fieldset>
			<legend>Check locations to print tickets and count. (onsite warehouses)</legend>

			<table class="infos">
				<tr>
					<% @check.locations.order("code ASC").each_with_index do |location, index| %>
						<td style="width: 30%">
						<%= check_box_tag("onsite_ids[]", location.id, false, :id => "location_#{location.id}") %>
						<%= label_tag "location_#{location.id}", location.code %></td>
						<%=raw("</tr><tr>") if (index + 1) % 3 == 0 %>
					<% end %>
				</tr>
			</table>
		</fieldset>

		<div class="buttons">
			<%= loading_submit f, "Finish", :class => 'button', 
					:message => 'Data import in progress. This process might take 5-10 minutes. Please wait for the process to complete. Do not close or refresh this webpage.' %>
		</div>

	<% end %>

</article>